### ISSUE TITLE
Uncaught DOMException: CanvasGradient.addColorStop: Invalid color

### ISSUE THREAD

**Issue by stockiNail** [kurkle/chartjs-plugin-gradient#20]
If you define in the color stop a non-color value, you get the following message:

```console
Uncaught DOMException: CanvasGradient.addColorStop: Invalid color
```

Because the plugin is leveraging on [@kurle/color](https://github.com/kurkle/color), I would suggest to check if the color is valid before adding to the gradient, and, if not valid, skips it.
I'm sorry but I didn't find the error before the last version release.

I'm going to submit a PR to fix it.

**Comment by kurkle** [comment]
Good, the last release did not run the action needed for npm release :)

**Comment by stockiNail** [comment]
FINE!! so we have time to fix it. I need some minutes....
