### ISSUE TITLE
 typo "module" (package.json).

### ISSUE THREAD

**Issue by uk-taniyama** [kurkle/chartjs-plugin-gradient#35]
package.json
`
"module": "dist/chartjs-plugin-gradient.ems.js"
`
ems -> esm.

so not found module by vite.

`
✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "chartjs-plugin-gradient". The package may have incorrect main/module/exports specified in its package.json.
`

**Comment by kurkle** [comment]
Thanks for the report!

**Comment by uk-taniyama** [comment]
Thanks all for the lighting fast response!
