### ISSUE TITLE
Got some problems in console

### ISSUE THREAD

**Issue by beastovsk** [kurkle/chartjs-plugin-gradient#39]
react-dom.development.js?ac89:22839 Uncaught TypeError: Cannot read properties of undefined (reading 'datasetIndex')
    at updateLegendItems (chartjs-plugin-gradient.esm.js?52eb:223:1)
    at Object.afterUpdate (chartjs-plugin-gradient.esm.js?52eb:339:1)

**Comment by stockiNail** [comment]
@beastovsk can you provide a sample in order to reproduce the issue?

**Comment by beastovsk** [comment]
Next.js, the application did not work with the errors that I indicated above. When opening a page with a component in which chartjs-plugin-gradient was located, the application crashed. After I removed the package from node_modules, everything worked.

**Comment by stockiNail** [comment]
I have created a sandbox which sounds working. https://codesandbox.io/s/nextjs-chartjs-demo-forked-n6561s
It's difficult to say what it's going wrong without any additional info.

**Comment by beastovsk** [comment]
To be honest, I have no idea what could have caused the error. Thank you for your time, if I get more information - I will send you
