### ISSUE TITLE
Why I am not able set the background to gradient even after following the steps

### ISSUE THREAD

**Issue by vikas-viki** [kurkle/chartjs-plugin-gradient#45]

**Comment by stockiNail** [comment]
@vikas-viki can you provide a sample to reproduce the issue you mentioned? In advance, if you are using line datasets, you could check if you set `fill: true` and/or if the `Filler` plugin has been registered.

**Comment by vikas-viki** [comment]
it is registered

**Comment by stockiNail** [comment]
> it is registered

can you provide a sample to reproduce the issue you mentioned?
